<?php
namespace app\controllers;

use app\helpers\UtilityHelper;
use app\helpers\ProductHelper;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;

class CheckoutController extends Controller
{
  public $total = 0;

  /**
   * {@inheritdoc}
   */
  public function beforeAction($action) {

    $session = Yii::$app->session;
    $session['product_layout'] = 'structure1';
    $session['home_page_url'] = '/';
    $session['order_page_url'] = '/order';

    return parent::beforeAction($action); // TODO: Change the autogenerated stub
  }

  /**
   * Displays homepage.
   *
   * @return string
   */
  public function actionIndex()
  {
    unset($_SESSION['promo_code']);
    return $this->render('index', ['checkout' => $this]);
  }
  
  public function actionUpdateCart(){
    if(isset($_REQUEST['product_key']) && isset($_REQUEST['is_subs'])) {
      $_SESSION['cart']['product']['is_subs'] = ($_REQUEST['is_subs'] == 'true') ? 1 : 0;
    }
  }

  public function getPromoCodeWithInfo() {

    $promo = FALSE;

    if(isset($_GET['promo_code']) && (isset($_SESSION['cart']) && !empty($_SESSION['cart']))){
      $total = $_SESSION['cart']['product']['amount'];
      
      $post_promo_code = trim($_GET['promo_code']);

      if(isset($_SESSION['promo_code'])) unset($_SESSION['promo_code']);

      if(array_key_exists($post_promo_code, Yii::$app->params['promo_codes'])) {
        $_SESSION['promo_code'] = Yii::$app->params['promo_codes'][$post_promo_code];
        $_SESSION['promo_code']['code'] = $post_promo_code;
        
        $promo_code = $_SESSION['promo_code'];
        $discount = $promo_code['discount'];

        if ($promo_code['type'] == 2) { // 2 = Percent Type
          $discount = number_format(($discount / 100) * $total, 2);
        }

        if ($total >= $discount):
          $this->total = number_format($total - $discount, 2);
          $discount =  number_format($discount, 2);
        else :
          $discount =  number_format(0, 2);
        endif;
        
        return $discount;
      }
    }
    return FALSE;
  }
}

