<?php

namespace app\controllers;

use yii\web\Controller;
use Yii;

class DmcaController extends Controller
{

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function beforeAction($action) {

        $session = Yii::$app->session;
        $session['product_layout'] = 'keto-cider';
        $session['home_page_url'] = '/';
        $session['order_page_url'] = '/order';

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
    public function actionIndex()
    {
        return $this->render('index', []);
    }
}
