<?php

namespace app\controllers;

use app\helpers\UtilityHelper;
use app\helpers\ProductHelper;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function beforeAction($action) {

        $session = Yii::$app->session;
        $session['product_layout'] = 'structure1';
        $session['home_page_url'] = '/';
        $session['order_page_url'] = '/order';

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],

            ],
            [ 'class' => AccessControl::className(),
              'only'  => ['login'],
              'rules' => [
                  [
                      'actions'  => ['login'],
                      'ips'     => UtilityHelper::getCustomParameters('ip_white_list'),
                      'allow'   => TRUE,
                      'roles'   => ['?'],
                  ],
              ],],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }


    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        //return $this->redirect(['/keto-cider']);

        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect('/admin/orders');
        }

        $model->password = '';
        return $this->render('@app/modules/admin/views/default/login.php', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
    }